Config = {}

Config.Animations = {

	{
		name  = 'festives',
		label = 'Festivos',
		items = {
			{label = "Fumar un cigarro", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING"}},
			{label = "Tocar la guitarra", type = "scenario", data = {anim = "WORLD_HUMAN_MUSICIAN"}},
			{label = "Dj", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@dj", anim = "dj"}},
			{label = "Beber cerveza 1", type = "scenario", data = {anim = "WORLD_HUMAN_DRINKING"}},
			{label = "Beber cerveza 2", type = "scenario", data = {anim = "WORLD_HUMAN_PARTYING"}},
			{label = "Tocar guitarra de aire", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@air_guitar", anim = "air_guitar"}},
			{label = "Air Shagging", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@air_shagging", anim = "air_shagging"}},
			{label = "Rock'n'roll", type = "anim", data = {lib = "mp_player_int_upperrock", anim = "mp_player_int_rock"}},
			-- {label = "Fumar un porro", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING_POT"}},
			{label = "Ebrio", type = "anim", data = {lib = "amb@world_human_bum_standing@drunk@idle_a", anim = "idle_a"}},
			{label = "Vomitar (vehiculo)", type = "anim", data = {lib = "oddjobs@taxi@tie", anim = "vomit_outside"}},
		}
	},

	{
		name  = 'greetings',
		label = 'Saludos',
		items = {
			{label = "Saludo simple", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_hello"}},
			{label = "Apretón de manos", type = "anim", data = {lib = "mp_common", anim = "givetake1_a"}},
			{label = "Saludo amistoso", type = "anim", data = {lib = "mp_ped_interaction", anim = "handshake_guy_a"}},
			{label = "Saludo (abrazo)", type = "anim", data = {lib = "mp_ped_interaction", anim = "hugs_guy_a"}},
			{label = "Saludo Militar", type = "anim", data = {lib = "mp_player_int_uppersalute", anim = "mp_player_int_salute"}},
		}
	},

	{
		name  = 'work',
		label = 'Trabajos',
		items = {
			{label = "Entregarse", type = "anim", data = {lib = "random@arrests@busted", anim = "idle_c"}},
			{label = "Pescar", type = "scenario", data = {anim = "world_human_stand_fishing"}},
			{label = "Investigar", type = "anim", data = {lib = "amb@code_human_police_investigate@idle_b", anim = "idle_f"}},
			{label = "Hablar por radio", type = "anim", data = {lib = "random@arrests", anim = "generic_radio_chatter"}},
			{label = "Circulación", type = "scenario", data = {anim = "WORLD_HUMAN_CAR_PARK_ATTENDANT"}},
			{label = "Binoculares", type = "scenario", data = {anim = "WORLD_HUMAN_BINOCULARS"}},
			{label = "Excavar", type = "scenario", data = {anim = "world_human_gardener_plant"}},
			{label = "Reparar el motor", type = "anim", data = {lib = "mini@repair", anim = "fixing_a_ped"}},
			{label = "Observar", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_KNEEL"}},
			{label = "Hablar con el cliente (vehiculo)", type = "anim", data = {lib = "oddjobs@taxi@driver", anim = "leanover_idle"}},
			{label = "Entregar factura", type = "anim", data = {lib = "oddjobs@taxi@cyi", anim = "std_hand_off_ps_passenger"}},
			{label = "Dar las compras", type = "anim", data = {lib = "mp_am_hold_up", anim = "purchase_beerbox_shopkeeper"}},
			{label = "Servir trago", type = "anim", data = {lib = "mini@drinking", anim = "shots_barman_b"}},
			{label = "Fotografiar", type = "scenario", data = {anim = "WORLD_HUMAN_PAPARAZZI"}},
			{label = "Fotografiar 2", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@photography", anim = "photography"}},
			{label = "Tomar notas", type = "scenario", data = {anim = "WORLD_HUMAN_CLIPBOARD"}},
			{label = "Martillar", type = "scenario", data = {anim = "WORLD_HUMAN_HAMMERING"}},
			{label = "Mendigar", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_FREEWAY"}},
			{label = "Estatua", type = "scenario", data = {anim = "WORLD_HUMAN_HUMAN_STATUE"}},
		}
	},

	{
		name  = 'humors',
		label = 'Humores',
		items = {
			{label = "Aplaudir", type = "scenario", data = {anim = "WORLD_HUMAN_CHEERING"}},
			{label = "Aprobación", type = "anim", data = {lib = "mp_action", anim = "thanks_male_06"}},
			{label = "Señalar a otro", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_point"}},
			{label = "Vení", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_come_here_soft"}}, 
			{label = "Provocar", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_bring_it_on"}},
			{label = "Señalarme", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_me"}},
			{label = "Lo sabia", type = "anim", data = {lib = "anim@am_hold_up@male", anim = "shoplift_high"}},
			--{label = "Etre épuisé", type = "scenario", data = {lib = "amb@world_human_jog_standing@male@idle_b", anim = "idle_d"}},
			--{label = "Je suis dans la merde", type = "scenario", data = {lib = "amb@world_human_bum_standing@depressed@idle_a", anim = "idle_a"}},
			{label = "Facepalm", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@face_palm", anim = "face_palm"}},
			{label = "Calmar ", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_easy_now"}},
			{label = "¿Que he hecho?", type = "anim", data = {lib = "oddjobs@assassinate@multi@", anim = "react_big_variations_a"}},
			{label = "Asustarse", type = "anim", data = {lib = "amb@code_human_cower_stand@male@react_cowering", anim = "base_right"}},
			{label = "Prepararse (pelear)", type = "anim", data = {lib = "anim@deathmatch_intros@unarmed", anim = "intro_male_unarmed_e"}},
			{label = "¡No es posible!", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_damn"}},
			{label = "Abrazar", type = "anim", data = {lib = "mp_ped_interaction", anim = "kisses_guy_a"}},
			{label = "Fuck You", type = "anim", data = {lib = "mp_player_int_upperfinger", anim = "mp_player_int_finger_01_enter"}},
			{label = "Masturbarse", type = "anim", data = {lib = "mp_player_int_upperwank", anim = "mp_player_int_wank_01", flag = 9}},
			{label = "Suicidarse (balazo)", type = "anim", data = {lib = "mp_suicide", anim = "pistol"}},
		}
	},

	{
		name  = 'sports',
		label = 'Deportes',
		items = {
			{label = "Marcar musculos", type = "anim", data = {lib = "amb@world_human_muscle_flex@arms_at_side@base", anim = "base"}},
			{label = "Barra de musculación", type = "anim", data = {lib = "amb@world_human_muscle_free_weights@male@barbell@base", anim = "base"}},
			{label = "Flexiones de brazos", type = "anim", data = {lib = "amb@world_human_push_ups@male@base", anim = "base", flag = 9}},
			{label = "Abdominales", type = "anim", data = {lib = "amb@world_human_sit_ups@male@base", anim = "base", flag = 9}},
			{label = "Hacer yoga", type = "anim", data = {lib = "amb@world_human_yoga@male@base", anim = "base_a", flag = 9}},
		}
	},
	{
		name  = 'dancing',
		label = 'Bailes',
		items = {
			{label = "Baile 1", type = "anim", data = {lib = "anim@amb@nightclub@dancers@club_ambientpeds@med-hi_intensity", anim = "mi-hi_amb_club_10_v1_male^6", flag = 9}},
			{label = "Baile 2", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@bodhi@ds@base", anim = "idle_a_fp", flag = 9}},
			{label = "Baile 3", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@bodhi@rds@base", anim = "idle_b", flag = 9}},
			{label = "Baile 4", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@std@ds@base", anim = "idle_a", flag = 9}},
			{label = "Baile 5", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim = "hi_dance_facedj_09_v2_male^6", flag = 9}},
			{label = "Baile 6", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@low_intesnsity", anim = "li_dance_facedj_09_v1_male^6", flag = 9}},
			{label = "Baile 7", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", anim = "trans_dance_facedj_hi_to_li_09_v1_male^6", flag = 9}},
			{label = "Baile 8", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_low_intensity", anim = "trans_dance_facedj_li_to_hi_07_v1_male^6", flag = 9}},
			{label = "Baile 9", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_13_v2_male^6", flag = 9}},
			{label = "Baile 10", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_hi_intensity", anim = "trans_dance_crowd_hi_to_li__07_v1_male^6", flag = 9}},
			{label = "Baile 11", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props@hi_intensity", anim = "hi_dance_prop_13_v1_male^6", flag = 9}},
			{label = "Baile 12", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props_transitions@from_med_intensity", anim = "trans_crowd_prop_mi_to_li_11_v1_male^6", flag = 9}},
			{label = "Baile 13", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_center_up", flag = 9}},
			{label = "Baile 14", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_right_up", flag = 9}},
			{label = "Baile 15", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@low_intensity", anim = "li_dance_crowd_17_v1_male^6", flag = 9}},
			{label = "Baile 16", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_med_intensity", anim = "trans_dance_facedj_mi_to_li_09_v1_male^6", flag = 9}},
			{label = "Baile Rak xD", type = "anim", data = {lib = "special_ped@zombie@monologue_4@monologue_4l", anim = "iamtheundead_11", flag = 9}},
			{label = "Baile 17", type = "anim", data = {lib = "timetable@tracy@ig_5@idle_b", anim = "idle_e", flag = 9}},
			{label = "Baile 18", type = "anim", data = {lib = "mini@strip_club@idles@dj@idle_04", anim = "idle_04", flag = 9}},
			{label = "Baile 19", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_1@monologue_1a", anim = "mtn_dnc_if_you_want_to_get_to_heaven", flag = 9}},
			{label = "Baile 20", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_4@monologue_4a", anim = "mnt_dnc_verse", flag = 9}},
			{label = "Baile 21", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_3@monologue_3a", anim = "mnt_dnc_buttwag", flag = 9}},
			{label = "Baile 22", type = "anim", data = {lib = "anim@amb@nightclub@dancers@black_madonna_entourage@", anim = "hi_dance_facedj_09_v2_male^5", flag = 9}},
			{label = "Baile 23", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props@", anim = "hi_dance_prop_09_v1_male^6", flag = 9}},
			{label = "Baile 24", type = "anim", data = {lib = "anim@amb@nightclub@dancers@dixon_entourage@", anim = "mi_dance_facedj_15_v1_male^4", flag = 9}},
			{label = "Baile 25", type = "anim", data = {lib = "anim@amb@nightclub@dancers@podium_dancers@", anim = "hi_dance_facedj_17_v2_male^5", flag = 9}},
			{label = "Baile 26", type = "anim", data = {lib = "anim@amb@nightclub@dancers@tale_of_us_entourage@", anim = "mi_dance_prop_13_v2_male^4", flag = 9}},
			{label = "Baile 27", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_cs", anim = "dance_loop_tao", flag = 9}},
			{label = "Baile 28", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_ig", anim = "dance_loop_tao", flag = 9}},
			{label = "Baile 29", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@uncle_disco", anim = "uncle_disco", flag = 9}},
			{label = "Baile 30", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@raise_the_roof", anim = "raise_the_roof", flag = 9}},
			{label = "Baile 31", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@cats_cradle", anim = "cats_cradle", flag = 9}},
			{label = "Baile 32", type = "anim", data = {lib = "anim@mp_player_intupperbanging_tunes", anim = "idle_a", flag = 9}},
			{label = "Baile 33", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center", flag = 9}},
			{label = "Baile 34", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_center", flag = 9}},
			{label = "Baile 35", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim = "high_center", flag = 9}},
			{label = "Baile 36", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@", anim = "trans_dance_facedj_hi_to_mi_11_v1_female^6", flag = 9}},
			{label = "Baile 37", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", anim = "trans_dance_facedj_hi_to_li_07_v1_female^6", flag = 9}},
			{label = "Baile 38", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v1_female^6", flag = 9}},
			{label = "Baile 39", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_09_v1_female^6", flag = 9}},
			{label = "Baile 40", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_06_base_laz", flag = 9}},
		}
	},

	{
		name  = 'misc',
		label = 'Diversos',
		items = {
			{label = "Beber cafe", type = "anim", data = {lib = "amb@world_human_aa_coffee@idle_a", anim = "idle_a"}},
			{label = "Sentarse", type = "anim", data = {lib = "anim@heists@prison_heistunfinished_biztarget_idle", anim = "target_idle", flag = 9}},
			{label = "Sentarse en el suelo 1", type = "anim", data = {lib = "amb@world_human_picnic@female@base", anim = "base", flag = 9}},
			{label = "Sentarse en el suelo 2", type = "anim", data = {lib = "amb@world_human_picnic@male@base", anim = "base", flag = 9}},
			{label = "Dormir 1", type = "anim", data = {lib = "amb@world_human_bum_slumped@male@laying_on_left_side@base", anim = "base", flag = 9}},
			{label = "Dormir 2", type = "anim", data = {lib = "amb@world_human_bum_slumped@male@laying_on_right_side@base", anim = "base", flag = 9}},
			{label = "Tirar Besos", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@blow_kiss", anim = "blow_kiss", flag = 9}},
			{label = "Besar 2", type = "anim", data = {lib = "anim@mp_player_intincarblow_kisslow@ds@", anim = "idle_a", flag = 9}},
			{label = "Esperar contra una pared", type = "scenario", data = {anim = "world_human_leaning"}},
			{label = "Acostarse en el suelo", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE_BACK"}},
			{label = "Cuerpo a tierra", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE"}},
			{label = "Pasar el trapo", type = "scenario", data = {anim = "world_human_maid_clean"}},
			{label = "Asar", type = "scenario", data = {anim = "PROP_HUMAN_BBQ"}},
			{label = "T-Pose", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_bj_to_prop_female", flag = 9}},
			{label = "Selfie", type = "scenario", data = {anim = "world_human_tourist_mobile"}},
			{label = "Escuchar a escondidas", type = "anim", data = {lib = "mini@safe_cracking", anim = "idle_base"}}, 
		}
	},

	{
		name  = 'attitudem',
		label = 'Actitudes',
		items = {
			{label = "Normal (Hombre)", type = "attitude", data = {lib = "move_m@confident", anim = "move_m@confident"}},
			{label = "Normal (Mujer)", type = "attitude", data = {lib = "move_f@heels@c", anim = "move_f@heels@c"}},
			{label = "Depresivo (Hombre)", type = "attitude", data = {lib = "move_m@depressed@a", anim = "move_m@depressed@a"}},
			{label = "Depresivo (Mujer)", type = "attitude", data = {lib = "move_f@depressed@a", anim = "move_f@depressed@a"}},
			{label = "Empresario", type = "attitude", data = {lib = "move_m@business@a", anim = "move_m@business@a"}},
			{label = "Decidido", type = "attitude", data = {lib = "move_m@brave@a", anim = "move_m@brave@a"}},
			{label = "Casual", type = "attitude", data = {lib = "move_m@casual@a", anim = "move_m@casual@a"}},
			{label = "Sobre-satisfecho", type = "attitude", data = {lib = "move_m@fat@a", anim = "move_m@fat@a"}},
			{label = "Hipster", type = "attitude", data = {lib = "move_m@hipster@a", anim = "move_m@hipster@a"}},
			{label = "Rengo", type = "attitude", data = {lib = "move_m@injured", anim = "move_m@injured"}},
			{label = "Intimidado", type = "attitude", data = {lib = "move_m@hurry@a", anim = "move_m@hurry@a"}},
			{label = "Drogado", type = "attitude", data = {lib = "move_m@hobo@a", anim = "move_m@hobo@a"}},
			{label = "Infeliz", type = "attitude", data = {lib = "move_m@sad@a", anim = "move_m@sad@a"}},
			{label = "Musculoso", type = "attitude", data = {lib = "move_m@muscle@a", anim = "move_m@muscle@a"}},
			--{label = "Choc", type = "attitude", data = {lib = "move_m@shocked@a", anim = "move_m@shocked@a"}},
			{label = "Oscuro", type = "attitude", data = {lib = "move_m@shadyped@a", anim = "move_m@shadyped@a"}},
			{label = "Cansado", type = "attitude", data = {lib = "move_m@buzzed", anim = "move_m@buzzed"}},
			{label = "Apresurado", type = "attitude", data = {lib = "move_m@hurry_butch@a", anim = "move_m@hurry_butch@a"}},
			{label = "Orgulloso", type = "attitude", data = {lib = "move_m@money", anim = "move_m@money"}},
			{label = "Apresurado 2", type = "attitude", data = {lib = "move_m@quick", anim = "move_m@quick"}},
			{label = "Sensual", type = "attitude", data = {lib = "move_f@maneater", anim = "move_f@maneater"}},
			{label = "Impertinente", type = "attitude", data = {lib = "move_f@sassy", anim = "move_f@sassy"}},	
			{label = "Arrogante", type = "attitude", data = {lib = "move_f@arrogant@a", anim = "move_f@arrogant@a"}},
		}
	},
	{
		name  = 'porn',
		label = '+18',
		items = {
			{label = "Felación (vehiculo-Activo)", type = "anim", data = {lib = "oddjobs@towing", anim = "m_blow_job_loop", flag = 9}},
			{label = "Felación (vehiculo-Pasivo)", type = "anim", data = {lib = "oddjobs@towing", anim = "f_blow_job_loop", flag = 9}},
			{label = "Felación (arrodillado-Activo)", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "pimpsex_punter", flag = 9}},
			{label = "Felación (arrodillado-Pasivo)", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "pimpsex_hooker", flag = 9}},
			{label = "Sexo (Vehiculo-Activo)", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_sex_loop_female", flag = 9}},
			{label = "Sexo (Vehiculo-Pasivo)", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_sex_loop_player", flag = 9}},
			{label = "Sexo (Parado-Activo)", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "shagloop_pimp", flag = 9}},
			{label = "Sexo (Parado-Pasivo)", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "shagloop_hooker", flag = 9}},
			{label = "Sexo (Vehiculo-Activo)2", type = "anim", data = {lib = "oddjobs@assassinate@vice@sex", anim = "frontseat_carsex_loop_m", flag = 9}}, 
			{label = "Sexo (Vehiculo-Pasivo)2", type = "anim", data = {lib = "oddjobs@assassinate@vice@sex", anim = "frontseat_carsex_loop_f", flag = 9}},
			{label = "Sexo (Vehiculo-Pasivo)3", type = "anim", data = {lib = "random@drunk_driver_2", anim = "cardrunksex_loop_f", flag = 9}},
			{label = "Rascarse genitales", type = "anim", data = {lib = "mp_player_int_uppergrab_crotch", anim = "mp_player_int_grab_crotch", flag = 9}},
			{label = "Seducir", type = "anim", data = {lib = "mini@strip_club@idles@stripper", anim = "stripper_idle_02"}},
			{label = "Seducir 2", type = "scenario", data = {anim = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"}},
			{label = "Mostrar los senos", type = "anim", data = {lib = "mini@strip_club@backroom@", anim = "stripper_b_backroom_idle_b"}},
			{label = "Sentarse para baile sensual", type = "anim", data = {lib = "mp_am_stripper", anim = "lap_dance_player"}},
			{label = "Baile sensual 1", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p1", anim = "ld_girl_a_song_a_p1_f"}},
			{label = "Baile sensual 2", type = "anim", data = {lib = "mini@strip_club@private_dance@part2", anim = "priv_dance_p2"}},
			{label = "Baile sensual 3", type = "anim", data = {lib = "mini@strip_club@private_dance@part3", anim = "priv_dance_p3"}},
			{label = "Baile sensual privado 1", type = "anim", data = {lib = "mp_am_stripper", anim = "lap_dance_girl"}},
			{label = "Baile sensual privado 2", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p2", anim = "ld_girl_a_song_a_p2_f"}},
			{label = "Baile sensual privado 3", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p3", anim = "ld_girl_a_song_a_p3_f"}},
			{label = "Baile sensual privado 4", type = "anim", data = {lib = "mini@strip_club@private_dance@part1", anim = "priv_dance_p1"}},

		}
	}
}